server:
  port: 8080
#  //sockettimeout解决上传文件超时问题
  tomcat:
        max-threads: 1000
        max-connections: 10000
        max-http-header-size: 1048576
        accept-count: 1000
        max-swallow-size: 1048576
        max-file-size: 100000000
        max-request-size: 200000000
spring:
  servlet:
    multipart:
      max-file-size: 100000000
      maxRequestSize: 200000000
  neo4j:
#      url: bolt://192.168.20.153:7687  #3.x
      url: neo4j://localhost:7687 #4.x
      username: neo4j
      password: 12345678
  datasource:
      url: jdbc:mysql://localhost:3306/kgdemo?useSSL=false&serverTimezone=UTC
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
mybatis:
  typeAliasesPackage: com.warmer.kgmaker.entity
  mapperLocations: classpath*:/mapping/*.xml
file:
  serverurl:  http://localhost:8080
  location : D:\\data\\   #如果是Windows情况下，格式是 D:\\kgmanager\\csv\\   linx 格式"/home/kgmanager/csv/";